### ISSUE TITLE
Default filter value

### ISSUE THREAD

**Issue by ImJustToNy** [simplesquid/nova-enum-field#32]
Hi!
Is there any way to set default value for `EnumFilter`?
By default, you need to define `default()` method inside your filter class, but I don't see any method to do it here.

Optional hack is to do something like:
```php
(new EnumFilter('foo', BarEnum::class))->withMeta([
    'currentValue' => BarEnum::Baz
]),
```

I can submit PR if desired.

**Comment by mdpoulter** [comment]
Hi @ImJustToNy. I don't think this has been included yet, no. Feel free to submit a PR with relevant tests for it! 👍 

Ideally, it should make use of the `default` method described in [the docs](https://nova.laravel.com/docs/3.0/filters/defining-filters.html#filter-default-values).
