### ISSUE TITLE
Enum column name "_backoffice" works fine, but "BACKOFFICE" shows empty value

### ISSUE THREAD

**Issue by martinschenk** [simplesquid/nova-enum-field#34]
I cant change the database column name because its used by others.
When the column name of the enum field is "_backoffice" the nove enum filed works perfect.
But when the column name is "BACKOFFICE" the nova enum column and filed shows empty.

<img width="786" alt="by default 2021-04-22 at 15 56 28" src="https://user-images.githubusercontent.com/635827/115727248-b7863000-a383-11eb-81af-d701f7055937.png">
<img width="126" alt="by default 2021-04-22 at 15 57 50" src="https://user-images.githubusercontent.com/635827/115727256-b9e88a00-a383-11eb-983d-acf449634298.png">
<img width="822" alt="by default 2021-04-22 at 15 58 26" src="https://user-images.githubusercontent.com/635827/115727262-ba812080-a383-11eb-89f8-5107b6dc3b69.png">
<img width="851" alt="by default 2021-04-22 at 15 58 42" src="https://user-images.githubusercontent.com/635827/115727266-bb19b700-a383-11eb-8dca-406a67db0d58.png">
<img width="616" alt="by default 2021-04-22 at 15 58 54" src="https://user-images.githubusercontent.com/635827/115727272-bbb24d80-a383-11eb-82ee-9ba119021859.png">

**Comment by mdpoulter** [comment]
Hi @martinschenk. Could you possibly provide some more details as it's difficult to work out what's going on?

**Comment by martinschenk** [comment]
Hi Matthew

Sorry for not explaining well.
The problem seems to be the database column name of the enum field.
If it’s written in capitalised letters like f.e. “COLUMN”, the nova enum
field shows empty.
And if the name of the column is f.e. “_column” it works everything
perfect.
Laravel 8. Php 7.4 MySQL 5.7 nova latest version




Regards, Martin



Matthew Poulter ***@***.***> schrieb am Do. 22. Apr. 2021 um
16:04:

**Comment by martinschenk** [comment]
here a more detailed explication:

the mysql database table has an enum column named "BACKOFFICE". 
The ENUM definition is: 'S','N', Allow NULL, Default N

Record 1 of the table has set the ENUM field to 'S'

I created the class SiNo:
        
        final class SiNo extends Enum
        {
            const S = 'S';
            const N = 'N';
        } 

My Model:

        class Perfil extends Model
        {
            use CastsEnums;
        
            protected $casts = [
                'BACKOFFICE' => SiNo::class
            ];

My Nova Model:

     Enum::make('BACKOFFICE')->attach(SiNo::class),


If i call now the nova page, 
- the index (list) view of the BACKOFFICE field shows up empty = "----" like in the first screenshot above.
- the edit field of the record shows: "choose an option" with the dropdown and the possibilities S and N. (But as you remember, in the database, there is set S.

----------

No i make just some very small changes to get it working:
1.) i change the name of the table from BACKOFFICE to _backoffice
2.) i change in the model 

        '_backoffice' => SiNo::class
3.) i change in the nova model

      Enum::make('_backoffice')->attach(SiNo::class),

Now it works all perfect!

In the list view i get the real database values and in the edit view he show also the correct values.

My problem:
As the database is used also by other services, i can not rename the column name from BACKOFFICE to _backoffice.

So how can i get it to work please?

mysql  Ver 14.14 Distrib 5.7.32, for osx10.15
PHP 7.4.16 (cli)
Laravel 8

**Comment by mdpoulter** [comment]
Thanks for the further details. I will see if I can replicate the problem this weekend.

**Comment by martinschenk** [comment]
Resolved.

I added in config/datababese.php

PDO::ATTR_CASE => PDO::CASE_LOWER

    'mysql' => [
          'options' => extension_loaded('pdo_mysql') ? array_filter([
                     PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
                     PDO::ATTR_CASE => PDO::CASE_LOWER
            ]) : [],
    ],

then i had to change all field names in the code to lowercase.

Now works, fine. Thanks

**Comment by mdpoulter** [comment]
Okay great! Glad to hear it. This sounds like quite an edge case scenario, so I'll close the issue for now unless someone else runs into it.
