### ISSUE TITLE
Is there any way to translate enumeration in field 

### ISSUE THREAD

**Issue by SirMishaa** [simplesquid/nova-enum-field#35]
Hello! 

I'm making a dashboard for French administrator, but for the relevance of the code, I obviously always use English.
The problem is that I don't see how to translate this, I haven't found any method to customize this on the field

![image](https://user-images.githubusercontent.com/42717232/128021593-2b6ff1a2-a0f1-4198-9dc0-f2cc334faee6.png)

My enum is declared like that : 
```php
<?php


namespace App\Enum;


use BenSampo\Enum\Enum;

final class StateType extends Enum
{
    const InStock = "in_stock";
    const OutStock = "out_stock";
    const DataNotAvailable = "data_not_available";
}
```

I would like to keep enum in English. Only the state in the select should be translated if possible.

**Comment by mdpoulter** [comment]
Hi @SirMishaa. Thanks for your question 😄 

Would the `LocalizedEnum` interface available in [BenSampo/laravel-enum](https://github.com/BenSampo/laravel-enum#enum-descriptions) perhaps work for this? I haven't tested it myself, but I can't see why it wouldn't work.
