### ISSUE TITLE
Support 4 version of bensampo/laravel-enum

### ISSUE THREAD

**Issue by vaiil** [simplesquid/nova-enum-field#41]
New version of bensampo/laravel-enum was released yesterday. 
Changelog: https://github.com/BenSampo/laravel-enum/blob/master/CHANGELOG.md#400---2021-11-09

**Comment by mpurdon** [comment]
@BenSampo any special considerations needed to make this upgrade?

**Comment by BenSampo** [comment]
No should be able to just bump the version.

It tagged it as a major version because there were significant changes to the localisation which has the potential to be breaking, but I don't think it will be in 99% of cases.

**Comment by mdpoulter** [comment]
Sorry for the delay all... Been a busy month!
