### ISSUE TITLE
Nova V4 support

### ISSUE THREAD

**Issue by dees040** [simplesquid/nova-enum-field#47]
Friendly reminder that Laravel Nova V4 released today. [Upgrade guide](https://nova.laravel.com/docs/4.0/upgrade.html).

**Comment by nathan-io** [comment]
Seconded, would love to have v4 support. And thanks for this package!

**Comment by nathan-io** [comment]
Just in case you didn't see the promo email about it, if you've purchased it any time in the last year, you already have a free unlimited v4 license in your Nova account. 

Otherwise, if you plan to use Nova in multiple projects over the next year, the new "Unlimited" license is discounted this week.

**Comment by mdpoulter** [comment]
Thanks to @brand7n I've published a release with v4 support. I still need to test if there's anything else which needs to change, so I'd appreciate any feedback.

**Comment by nathan-io** [comment]
We have a project I can try this out in next week. I do hope that `composer.json` update is truly all that's needed, but based on these docs, I'm doubtful of that:

- https://nova.laravel.com/docs/4.0/upgrade.html#high-impact-changes
- https://nova.laravel.com/docs/4.0/upgrade.html#updating-custom-tool-cards-fields-filters

**Comment by brand7n** [comment]
@nathan-io All I use is SimpleSquid\Nova\Fields\Enum, but it is working for me. EnumFilter and EnumBooleanFilter probably just need to be updated to use NovaRequest instead of Illuminate\Http\Request.

**Comment by brand7n** [comment]
FWIW I don't see any issues with EnumFilter or EnumBooleanFilter either
