### ISSUE TITLE
Filter shows selected enum option even when all enum options are unchecked

### ISSUE THREAD

**Issue by asugai** [simplesquid/nova-enum-field#53]
Laravel v9.41.0
Nova v4.19.3
Nova Enum Field v3.0.1

**Issue:** 
The **Filter** dropdown shows that an enum filter is selected even when filters have been unchecked.

**Steps to reproduce:**
- Check off 1 enum filter option
- See "Selected Filter Counter" change to "1" and background color change from "white" to "green"
- Uncheck the enum filter option
- See "Selected Filter Counter" stay at "1" and background color stays "green"

**Expected results:**
- See "Selected Filter Counter" show no counter and background color change back to "white"

<img width="313" alt="Screenshot 2022-12-12 at 10 16 20 PM" src="https://user-images.githubusercontent.com/2228791/207227955-e1c55742-ed46-47d1-9e36-66acbd907998.png">

**Comment by mdpoulter** [comment]
Seemed to have missed this over the holidays! Happy with a PR that resolves this 😄

**Comment by zatorck** [comment]
Hey, do you still need PR for that? I can try to do it.

**Comment by mdpoulter** [comment]
Sure!

**Comment by zatorck** [comment]
I already found that workaround for that is not to use "0" as value of enum. eg. `const Admin = 0;`. I'm will fix it soon.

**Comment by mdpoulter** [comment]
Closing this if this behaviour is present in Nova itself. Thanks for the investigation!
