### ISSUE TITLE
Not working with Laravel Nova 4.32.12 (Feb 14)

### ISSUE THREAD

**Issue by couchlab-pl** [simplesquid/nova-enum-field#56]
After update sth is wrong with validation, cannot save any field with enum type.

**Comment by mdpoulter** [comment]
@couchlab-pl Sorry for the delayed response. Is this still an issue for you?

**Comment by mdpoulter** [comment]
I suspect this will be resolved with https://github.com/simplesquid/nova-enum-field/releases/tag/v3.2.0 , but let me know if it's not.
