### ISSUE TITLE
Attribute Casting Assumption

### ISSUE THREAD

**Issue by ddevdreamer** [simplesquid/nova-enum-field#6]
Thank you for this package.

You're assuming that the Model uses Attribute Casting by default which is okay but please mention it in the documentation since you're relying on it. Otherwise, "Trying to get property 'value' of non-object" error would be thrown.

Thank you again.

**Comment by smualex** [comment]
> Thank you for this package.
> 
> You're assuming that the Model uses Attribute Casting by default which is okay but please mention it in the documentation since you're relying on it. Otherwise, "Trying to get property 'value' of non-object" error would be thrown.
> 
> Thank you again.

How would I set up my model 

> Thank you for this package.
> 
> You're assuming that the Model uses Attribute Casting by default which is okay but please mention it in the documentation since you're relying on it. Otherwise, "Trying to get property 'value' of non-object" error would be thrown.
> 
> Thank you again.

Can you give an example on how to set this up? Fairly new to Laravel and running into this issue. Thanks!

**Comment by mdpoulter** [comment]
Thanks for picking that up! :) I have updated the documentation accordingly.
